### ISSUE TITLE
Timestamp columns aren't seen as timestamps

### ISSUE THREAD

**Issue by ttilberg** [jrgns/sequel-elasticsearch#2]
I've found that when I load records from Sequel into ElasticSearch, I always have to remap the DateTime columns with `#iso_8601` for it to get picked up as a timestamp in ES.

I use SQL Server and Sequel/TinyTds and I'm not sure if folks on Postgres and others experience the same issues.

For example, when running `a_model_object.db_schema.map{|col, v| [col, v[:db_type] ]}`, I can see each of the data types, and I know that `datetime` columns need special attention in ES before I send the data.

While learning about ES, I've been loading my data using the bulk method with methods that look like this:

```
def format_record values
  values[:started_at] = values[:started_at] && values[:started_at].iso8601
  values[:completed_at] = values[:completed_at] && values[:completed_at].iso8601
  [
    { index: { _index: 'jobs', _type: 'job', _id: values[:id] } },
    values
  ]
end
```
In my research, it seems to be an issue with the value formatted from Ruby's `Time.new.to_s`

The above example could obviously be refactored to be a bit more dynamic, perhaps something along the lines of `values.each{|k,v| values[k] = v.iso_8601 if v.is_a? Time}`

Trying to [force the mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html)  explicitly in elasticsearch as `date` yields messages like:

```
"Invalid format: \"2018-02-06 04:38:47 -0600\" is malformed at \" 04:38:47 -0600\""
```

Essentially, as far as I can tell, all `DateTime` columns / ruby Time objects should be converted to `#iso_8601` before being loaded for es to see it correctly. But I'm very new to ES, so I may be missing something.

**Comment by jrgns** [comment]
I think you're right. I'll run a couple of tests to see what I can do.

**Comment by ttilberg** [comment]
Here's some additional background on the problem at hand:

https://github.com/elastic/elasticsearch-ruby/issues/44

At the end, they mention that Rails is fixing the formatting for them, which is probably why this hasn't otherwise gotten much attention. 

As mentioned in the thread, looping through the object just to check for `Time` attributes could be expensive, particularly when unnecessary. Maybe a goal could be to implement transformation options on your model class, like `elastic_formatter :created_at, c -> { c.iso8601 }`. As you call the method in your class definition, you are adding mini etl operations to wash your object with. Then during the index method, you can iterate through the formatters...

This is a bit beyond my ability in Ruby to consider, so this might be nuts and frothing with bad ideas.

**Comment by jrgns** [comment]
I've fixed it by looping through the values (for now). If it leads to performance issues, we'll fix it then.

The biggest thing is to format the date in such a way that Elasticsearch can automatically pick up that the field is a date.
