### ISSUE TITLE
Need flexible way to modify/extend indexed values list

### ISSUE THREAD

**Issue by pjfitzgibbons** [jrgns/sequel-elasticsearch#3]
Hello,

I'm working on a parity to ElasticSearch-Rails, which adds an overridable method to ActiveRecord::Model::InstanceVariables for the indexed values (#as_indexed_json).

So, for Sequel::Elasticsearch, I'm thinking of adding InstanceMethods#indexed_values to lib/sequel/plugins/elasticsearch.rb with default implementation simply return Sequel::Model#values.
Then  modify #index_document to use #indexed_values.

I'll be working on this sometime in the next couple of weeks.  Just to let you know this issue is on my radar.  I"ve forked the project for my dev.

Kindest Regards,
Peter Fitzgibbons

**Comment by jrgns** [comment]
@pjfitzgibbons Thanx! I've been thinking about the same thing, but haven't had the motivation to get on it. Feel free to ping me if you want to chat it through.

**Comment by jrgns** [comment]
Oh, and I'm happy with the way you want to implement it.
