### ISSUE TITLE
index-name parity with Elasticsearch::Model gem

### ISSUE THREAD

**Issue by pjfitzgibbons** [jrgns/sequel-elasticsearch#5]
Hello,
I am writing a worker-component with sequel-elasticsearch whose index must also be read by an equivalent ActiveRecord model with Elasticsearch::Model plugin.
I am not seeing the same results between the two.

I am seeing this for ElasticSearch::Model index name:
```
# class Forum < ActiveRecord::Base
#       include Elasticsearch::Model
#      index_name "throtl-admin-forum-#{Rails.env}"
Forum.__elasticsearch__.index_name
=> "throtl-admin-forum-development"
```
And this for sequel-elasticsearch index name:
```
#    class Forum < Sequel::Model
#      env = ENV['RAILS_ENV'] || 'development'
#      plugin :elasticsearch,
#             index: "throtl-admin-forum-#{env}".to_sym
Scraper::DB::Forum.elasticsearch_index
 => :"throtl-admin-forum-development"
```
So:
`"throtl-admin-forum-development" # Elasticsearch::Model`
vs
`:"throtl-admin-forum-development" # sequel-elasticsearch`

I think the issue is that the sequel-elasticsearch index name somehow has the quotes captured in the symbolized index name?   I even tried to force-symbolize the key in my code above, without affect.

Could you tell me if you have any ideas how this can be done correctly?

Thanks and Kindest Regards,
Peter Fitzgibbons

**Comment by jrgns** [comment]
@pjfitzgibbons If you remove the `to_sym` from the `sequel-elasticsearch` index you'll get the same result.

The active record method returns a string, where as the sequel method returns a symbol.

**Comment by pjfitzgibbons** [comment]
I still get the same result after removing .to_sym from the :index declaration:
```
#    class Forum < Sequel::Model
#      env = ENV['RAILS_ENV'] || 'development'
#      plugin :elasticsearch,
#             index: "throtl-admin-forum-#{env}".to_sym
Scraper::DB::Forum.elasticsearch_index
 => :"throtl-admin-forum-development"
