### ISSUE TITLE
Usage query

### ISSUE THREAD

**Issue by danielwpz** [jrgns/sequel-elasticsearch#6]
Hey, if i'm using the plugin in this way:
```ruby
class Document < Sequel::Model
  plugin :elasticsearch
end
```
How could I specify the config for elasticsearch? such like username/password?
I saw you wrote
```ruby
Sequel::Model.plugin :elasticsearch,
  elasticsearch: { log: true }, # Options to pass the the Elasticsearch ruby client
  index: 'all-my-data', # The index in which the data should be stored. Defaults to the table name associated with the model
  type: 'is-mine' # The type in which the data should be stored.
```
but where should I put this？

**Comment by jrgns** [comment]
@danielwpz If you use it for a single model, you pass the options in the same way:

```ruby
class Document < Sequel::Model
  plugin :elasticsearch, elasticsearch: { log: true, user: 'MyUser', password: 'SomePass' }
end
```

See the [Client docs](https://www.rubydoc.info/gems/elasticsearch-transport#Connect_using_an_Elastic_Cloud_ID) for the properties you can pass in the `elasticsearch` hash.

**Comment by danielwpz** [comment]
hey, yeah I figured it out eventually lol. Thanks!
