### ISSUE TITLE
Index type

### ISSUE THREAD

**Issue by danielwpz** [jrgns/sequel-elasticsearch#7]
Hey I have another question, why here you are using `sync` as default type instead of `_doc`?         

Since the request will be `PUT elasticsearch/index/sync/id` instead of `PUT elasticsearch/index/_doc/id`      

https://github.com/jrgns/sequel-elasticsearch/blob/d87efdacd8af315b757460b33ed59f049df05d56/lib/sequel/plugins/elasticsearch.rb#L29

**Comment by jrgns** [comment]
@danielwpz Good catch. I wrote this before I was fully aware of the Elasticsearch switch to _doc as the default type. I'll make a change to fix it.

**Comment by jrgns** [comment]
@danielwpz I've fixed this in the latest release - v0.4.5
