### ISSUE TITLE
batch update on Elastic based on ids

### ISSUE THREAD

**Issue by gencer** [jrgns/sequel-elasticsearch#8]
I update models in batch like this:

```
Email.where(user_id: user.id, guid: guids).update(...)
```

So, hooks are not called. Is there a way to invoke and update affected ids/guids (which is available on es)? For example;

```
Email.update_es!(dataset: Email.where(guid: guids))
```

This will force update all emails based on dataset

**Comment by gencer** [comment]
In source, i see that `import!` updates existing dataset against es. However, When I do:

```
Mailbox::Email.import! dataset: Mailbox::Email.where(user_id: user.id, guid: emails)
```

I get:

> `[404] {"error":"alias [mail-emails] missing","status":404}`

**Comment by gencer** [comment]
A simple `sync!` method that i made from `import!` solved my problem.
```
        def sync!(dataset: nil, batch_size: 100)
          dataset ||= self.dataset

          # Index all the documents
          body = []
          dataset.each_page(batch_size) do |ds|
            body = []
            ds.all.each do |row|
              print '.'
              body << {
                update: {
                  _index: elasticsearch_index,
                  _type: elasticsearch_type,
                  _id: row.document_id,
                  data: { doc: row.indexed_values, doc_as_upsert: true }
                }
              }
            end
            puts '/'
            es_client.bulk body: body
            body = nil
          end
        end
```

**Comment by jrgns** [comment]
@gencer I'll check it out. IIRC, the `import!` method relies on an existing alias, which which might not be created properly when not using the `reindex!` method.

**Comment by jrgns** [comment]
@gencer I've pushed a fix for this. If no index is specified and it can't find the last index, it will used the configured index. So you can now just do

```ruby
Mailbox::Email.import! dataset: Mailbox::Email.where(user_id: user.id, guid: emails)
```

**Comment by gencer** [comment]
@jrgns, Awesome! Thank you! ❤🎉
