### ISSUE TITLE
[types removal] Specifying types in bulk requests is deprecated.

### ISSUE THREAD

**Issue by gencer** [jrgns/sequel-elasticsearch#9]
When I try to bulk import via:

```ruby
Mailbox::Email.import! dataset: Mailbox::Email.where { ...conditions }
```
It does the job but I get following warning. Elasticsearch seems deprecated this feature and probably will remove on upcoming versions.

```log
warning: 299 Elasticsearch-7.10.0-51e9d6f22758d0374a0f3f5c6e8f3a7997850f96 "[types removal] Specifying types in bulk requests is deprecated."
```

What is/are our option(s) in here?

**Comment by jrgns** [comment]
@gencer I've already started to accommodate that. What settings do you specify when activating the plugin?

**Comment by gencer** [comment]
Hi @jrgns. I use model like this:

```ruby
class MyModel < Sequel::Model
    plugin :elasticsearch,
           index: 'mail-emails',
           type: 'mail-email'
end
```

**Comment by jrgns** [comment]
Yeah, it's the type setting that's the problem. You'll need to stop using custom types, and then not specify it when activating the plugin.

**Comment by gencer** [comment]
Ah! I thought the opposite on this. Okay then, Removed it.

Thank you for your reply. I'm closing this issue now!
